image: mhart/alpine-node:0.10

stages:
  - test
  - build
  - deploy


test:
  stage: test
  script:
    - npm -d install
    - npm test
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public

pages:
  stage: build
  artifacts:
    paths:
    - public
  only:
  - master


build_image:
  stage: build
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/gbraad/gauth:latest .
    - docker push registry.gitlab.com/gbraad/gauth:latest

